### ISSUE TITLE
Light mode in about page

### ISSUE THREAD

**Issue by RubenPX** [ragestudio/comty#73]
**Describe the bug:** 

About section displays only in light mode (This only happens in production environment)

**Screenshots or/and Reproductions(if applicable):** 

https://preview.comty.pw/about

![image](https://user-images.githubusercontent.com/23123160/198155351-f837de2b-3acd-4ee8-b747-f6e23c4523d2.png)

## Styles

Dev mode: 
![image](https://user-images.githubusercontent.com/23123160/198167261-1ba56472-63c8-4aca-8650-d354692db705.png)

Prod mode:
![image](https://user-images.githubusercontent.com/23123160/198167310-206e7644-a45f-4897-bfee-8e449fff4157.png)

**Comment by srgooglo** [comment]
This is caused because some layout libraries have their own css variables.

Should be fixed on 6f7f57a3c6e6ca9eb067e86574433b5342acf580
