### ISSUE TITLE
Failed on load react-router-dom

### ISSUE THREAD

**Issue by RubenPX** [ragestudio/comty#87]
**Describe the bug:** 

React router dom, does not found (latest commit tested: https://github.com/ragestudio/comty/commit/739c110b4a1b6dfdfca9d0bd03052a829f73c9f2)

npm dependencies yet installed

**Screenshots or/and Reproductions(if applicable):** 

![image](https://user-images.githubusercontent.com/23123160/212195496-4fa27e03-8b51-4322-b80d-1fd0eb6fdfe2.png)

**Comment by srgooglo** [comment]
Try with a fresh dependency installation.

**Comment by RubenPX** [comment]
![image](https://user-images.githubusercontent.com/23123160/212196413-fb9f37dd-c5ee-49dc-bafd-d1c67b87b157.png)

Nope... Tomorrow i will download full repo to test it

![image](https://user-images.githubusercontent.com/23123160/212196641-700da266-80f7-4a7e-9369-36ebf1984845.png)

**Comment by RubenPX** [comment]
It worked!!

![image](https://user-images.githubusercontent.com/23123160/212282859-d9371003-4c7c-47bd-bb07-6514cc2bd8ef.png)

![image](https://user-images.githubusercontent.com/23123160/212283693-7f7fb61a-4705-4d8e-a2b4-ee62ea7aaf3c.png)
